name: Docs Link

on: [status]

jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-20.04
    steps:
    - uses: larsoner/circleci-artifacts-redirector-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        artifact-path: 0/html/index.html
        circleci-jobs: build-Docs
        job-title: Check the rendered docs here!
